### ISSUE TITLE
What are the frequency bands?

### ISSUE THREAD

**Issue by Flosseraptor** [googleprivate/resonance-audio-unity-sdk#77]
Hello, 
I am doing my PhD research on VR and immersive audio. I am wanting to compare RT60s that I have captured from a real location with those that Resonance Audio creates. I have searched through all the scripts to try and find what the frequency bands are so I can compare my results, but I cannot find them anywhere. Is there any place I could find the frequency bands? 

Thanks!

**Comment by anokta** [comment]
hi, you can see the definition of the frequency bands used in the source code here: https://github.com/resonance-audio/resonance-audio/blob/1f68420412cdde70fa3c66d73b8fb5d8c065c8d3/resonance_audio/base/constants_and_types.h#L129

**Comment by Flosseraptor** [comment]
> hi, you can see the definition of the frequency bands used in the source code here: https://github.com/resonance-audio/resonance-audio/blob/1f68420412cdde70fa3c66d73b8fb5d8c065c8d3/resonance_audio/base/constants_and_types.h#L129

Thank you so so much!! You are amazing!
